-- ═══════════════════════════════════════════════════════════════════════════
-- iffy.ai — Initial Database Schema
-- Run this in the Supabase SQL editor (Dashboard > SQL Editor > New Query)
-- ═══════════════════════════════════════════════════════════════════════════

-- Enable UUID extension (usually already enabled in Supabase)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ─── simulations ──────────────────────────────────────────────────────────
-- Stores each complete simulation generated by /api/simulate

CREATE TABLE IF NOT EXISTS simulations (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title       TEXT NOT NULL,
  scenario    TEXT NOT NULL,
  simulation_json JSONB NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for fast lookups by creation time (for future history features)
CREATE INDEX IF NOT EXISTS idx_simulations_created_at ON simulations (created_at DESC);

-- ─── mutations ────────────────────────────────────────────────────────────
-- Stores each mutation (follow-up condition) applied to a simulation

CREATE TABLE IF NOT EXISTS mutations (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  simulation_id   UUID NOT NULL REFERENCES simulations(id) ON DELETE CASCADE,
  mutation_prompt TEXT NOT NULL,
  mutation_json   JSONB NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mutations_simulation_id ON mutations (simulation_id);

-- ─── debates ──────────────────────────────────────────────────────────────
-- Stores debate sessions (participants + messages) linked to a simulation

CREATE TABLE IF NOT EXISTS debates (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  simulation_id UUID NOT NULL REFERENCES simulations(id) ON DELETE CASCADE,
  messages      JSONB NOT NULL DEFAULT '[]',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_debates_simulation_id ON debates (simulation_id);

-- ─── Row Level Security ────────────────────────────────────────────────────
-- Allow public read access (no auth required for MVP).
-- The service-role key used server-side bypasses RLS entirely.

ALTER TABLE simulations ENABLE ROW LEVEL SECURITY;
ALTER TABLE mutations   ENABLE ROW LEVEL SECURITY;
ALTER TABLE debates     ENABLE ROW LEVEL SECURITY;

-- Public read policy (MVP — tighten for production)
CREATE POLICY "Allow public read simulations"
  ON simulations FOR SELECT USING (true);

CREATE POLICY "Allow public read mutations"
  ON mutations FOR SELECT USING (true);

CREATE POLICY "Allow public read debates"
  ON debates FOR SELECT USING (true);

-- Only the service-role (server) can write
-- (These are implicit since service-role bypasses RLS)
