import { z } from "zod";

/** A debate participant persona generated by the AI. */
export const ParticipantSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  role: z.string().min(1),
  stance: z.enum(["supportive", "opposed", "neutral", "conflicted"]),
  biases: z.array(z.string()),
  personality: z.string().min(1),
  concerns: z.array(z.string()).min(1),
  goals: z.array(z.string()).min(1),
});

/** A single message spoken by a participant. */
export const DebateMessageSchema = z.object({
  speaker_id: z.string().min(1),
  message: z.string().min(1),
  emotion: z.enum([
    "excited",
    "concerned",
    "angry",
    "hopeful",
    "skeptical",
    "neutral",
    "passionate",
    "resigned",
  ]),
  stance_strength: z.number().min(0).max(1),
});

/** The full debate payload (participants + opening messages). */
export const DebateSchema = z.object({
  participants: z.array(ParticipantSchema).min(3),
  messages: z.array(DebateMessageSchema).min(3),
});

export type Participant = z.infer<typeof ParticipantSchema>;
export type DebateMessage = z.infer<typeof DebateMessageSchema>;
export type Debate = z.infer<typeof DebateSchema>;
