/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppImpactsRouteImport } from './routes/app.impacts'
import { Route as AppFlowRouteImport } from './routes/app.flow'
import { Route as AppDebateRouteImport } from './routes/app.debate'

const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppImpactsRoute = AppImpactsRouteImport.update({
  id: '/impacts',
  path: '/impacts',
  getParentRoute: () => AppRoute,
} as any)
const AppFlowRoute = AppFlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => AppRoute,
} as any)
const AppDebateRoute = AppDebateRouteImport.update({
  id: '/debate',
  path: '/debate',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/marketplace': typeof MarketplaceRoute
  '/saved': typeof SavedRoute
  '/app/debate': typeof AppDebateRoute
  '/app/flow': typeof AppFlowRoute
  '/app/impacts': typeof AppImpactsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/marketplace': typeof MarketplaceRoute
  '/saved': typeof SavedRoute
  '/app/debate': typeof AppDebateRoute
  '/app/flow': typeof AppFlowRoute
  '/app/impacts': typeof AppImpactsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/marketplace': typeof MarketplaceRoute
  '/saved': typeof SavedRoute
  '/app/debate': typeof AppDebateRoute
  '/app/flow': typeof AppFlowRoute
  '/app/impacts': typeof AppImpactsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/community'
    | '/marketplace'
    | '/saved'
    | '/app/debate'
    | '/app/flow'
    | '/app/impacts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/community'
    | '/marketplace'
    | '/saved'
    | '/app/debate'
    | '/app/flow'
    | '/app/impacts'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/community'
    | '/marketplace'
    | '/saved'
    | '/app/debate'
    | '/app/flow'
    | '/app/impacts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  MarketplaceRoute: typeof MarketplaceRoute
  SavedRoute: typeof SavedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/impacts': {
      id: '/app/impacts'
      path: '/impacts'
      fullPath: '/app/impacts'
      preLoaderRoute: typeof AppImpactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/flow': {
      id: '/app/flow'
      path: '/flow'
      fullPath: '/app/flow'
      preLoaderRoute: typeof AppFlowRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/debate': {
      id: '/app/debate'
      path: '/debate'
      fullPath: '/app/debate'
      preLoaderRoute: typeof AppDebateRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDebateRoute: typeof AppDebateRoute
  AppFlowRoute: typeof AppFlowRoute
  AppImpactsRoute: typeof AppImpactsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDebateRoute: AppDebateRoute,
  AppFlowRoute: AppFlowRoute,
  AppImpactsRoute: AppImpactsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  MarketplaceRoute: MarketplaceRoute,
  SavedRoute: SavedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
